name: Update README

on:
  push:
    branches:
      - main

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Generate content
        run: echo "This is the content to add to the README file." > README_CONTENT.md

      - name: Append content to README file
        run: cat README_CONTENT.md >> README.md

      - name: Check repository status
        run: |
          git status

      - name: Stage changes
        run: |
          git add README.md

      - name: Commit changes
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git commit -m "Update README file"
          git push

      - name: Update README file
        uses: actions/github-script@v4
        with:
          script: |
            const fs = require('fs');
            const content = fs.readFileSync('README.md', 'utf8');
            const newContent = content.replace(/<!--START_SECTION:update-->[\s\S]*<!--END_SECTION:update-->/g, `<!--START_SECTION:update-->\n${fs.readFileSync('README_CONTENT.md', 'utf8')}\n<!--END_SECTION:update-->`);
            fs.writeFileSync('README.md', newContent);
